version: '3.4'

services:
  sourcingdb:
    image: mongo

  esourcing.products:
    image: ${DOCKER_REGISTRY-}esourcing
    build:
      context: .
      dockerfile: src/Services/Products/ESourcing.Products/Dockerfile
